language: go
go:
  - "1.10"
before_install:
  - curl -sSL https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
install:
  - dep ensure
test:
  - go test -v ./...
  - go build -o bear main.go
before_deploy:
  - zip -r9 -qT bear.zip . -i bear
deploy:
  provider: releases
  skip_cleanup: true
  file: "bear.zip"
  on:
    tags: true
notifications:
  email: false
  slack: bjacobel:xasDl3nTxo2feJGba70E43oR
