language: go
go:
  - "1.10"
before_install:
  - curl -sSL https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
install:
  - dep ensure
test:
  - go test -v ./...
before_deploy:
  - go build -o bear main.go
deploy:
  provider: releases
  on:
    all_branches: true
notifications:
  email: false
  slack: bjacobel:xasDl3nTxo2feJGba70E43oR
